export const OPANUJ_FRONTEND_AGENDA = [
  'Witaj w kursie Opanuj Frontend: AI Edition',
  'Praca z rozszerzeniami AI Edition',
  'Czysty kod na frontendzie',
  'Dobre praktyki i refaktoryzacja kodu',
  'Wzorce projektowe w warstwie client-side',
  'Czym jest zarządzanie stanem na frontendzie?',
  'Zarządzanie stanem lokalnym i współdzielonym',
  'Architektura Flux i lekcje z mody na Reduxa',
  'Zarządzanie stanem globalnym',
  'Techniki komunikacji frontendu z API',
  'Obsługa wielu zapytań - metody obiektu Promise',
  'Incydenty na produkcji i obsługa błędów',
  'Metryki wydajności aplikacji',
  'Optymalizacja wydajności aplikacji',
  '⚡️ AI Edition - Pair programming z AI (Update - IV Edycja)',
  'Wprowadzenie do testowania oprogramowania',
  'Testy jednostkowe i testy komponentów',
  'Wprowadzenie do testów e2e i Playwright',
  'Najlepsze praktyki testów e2e',
  'Bezpieczna komunikacja z API',
  'Walidacja i spójność danych',
  'Czym jest dostępność (a11y)?',
  'Semantyczny HTML',
  'Najważniejsze techniki a11y',
  'Praktyki inżynierii jakości',
  'Zespół dbający o jakość',
  '⚡️ AI Edition - Jakość z asystentem AI (Update - IV Edycja)',
  'Aplikacja w trybie produkcyjnym',
  'Pierwsze wdrożenie na chmurę',
  'Kontrolowane wdrożenia z GitHub Actions',
  'Zaawansowane CI/CD z GitHub Actions',
  'Praca na wielu środowiskach',
  'Wdrożenie na chmurę AWS',
  'Infrastruktura jako kod',
  'Wysoka dostępność aplikacji',
  'Monitoring client-side z Sentry',
  'Konfiguracja alarmów w systemach produkcyjnych',
  'Feature toggle w aplikacji frontendowej',
  'Eksperymenty funkcjonalne i testy A/B',
  '⚡️ AI Edition - Utrzymanie produkcji z AI (Update - IV Edycja)',
  'Czym jest Design System?',
  'Komponenty w design systemach',
  'Rejestry i menadżery pakietów',
  'Rozwój i publikacja biblioteki',
  'Innersource i prywatne repozytoria pakietów',
  'Obsługa repozytorium CodeArtifact',
  'Monorepozytoria na frontendzie',
  'Praca z monorepo',
  'Efektywna współpraca w repozytorium',
  'Ciągła nauka poprzez feedback',
  '⚡️ AI Edition - Procesy zespołowe z AI',
  'Planowanie architektury projektu',
  'Stack technologiczny projektu',
  'Złożoność i monolity',
  'Cechy projektów wysokiej jakości',
  'Metodologia Feature-Sliced Design',
  'Praktyki dużej skali - Mikrofrontendy',
  'Ścieżka lidera technicznego frontendu',
  'Umiejętności miękkie lidera technicznego',
  '⚡️ AI Edition - Odcinek specjalny',
];

export const OPANUJ_FRONTEND_LIVE_AGENDA = [
  'Oskar Dudycz - Systemy event-driven z TypeScript',
  'Piotr Kowalski - Rozwój programisty dzięki Open Source',
  'Tomasz Kielar - Full-stack development na 2025r.',
  'Michał Michalczuk - Testowanie komponentów w Storybook',
  'Tomasz Ducin - Domain-Driven Design na froncie',
  'Kacper Sokołowski - Case study nowej architektury Hotjar',
  'Filip Mamcarczyk - Dobre praktyki zespołowe',
  'Wojciech Trawiński - CI/CD na produkcji',
  'Ola Kunysz - Testowanie kodu',
  'Andrzej Fricze - Frontend w 2024',
  'Kaja Stefaniak - Tajniki rekrutacji',
  'Wiktor Jamro - Architektura - technologia vs biznes',
  'Sebastian Sędzik - Polyrepo vs monorepo',
  'Adam Gospodarczyk - AI w akcji',
  'Olaf Sulich - Dostępność na frontendzie',
];

export const OPANUJ_TS_CORE_PRO_AGENDA = [
  'Wprowadzenie do kursu Opanuj TypeScript',
  'Pierwsze kroki z TypeScriptem',
  'Tajniki kompilatora TypeScript',
  'Wprowadzenie do systemu typów',
  'Typy jako zbiory wartości',
  'Typy nieznane i wartości puste',
  'Wprowadzenie do typów generycznych',
  'Ograniczenia na parametrach generyków',
  'Wbudowane typy pomocnicze',
  'Typy generyczne w kodzie produkcyjnym',
  'Typy mapowane',
  'Typy w szablonach stringów',
  'Typy warunkowe',
  'Mechanizm dedukcji typów - infer',
  'Moduły, skrypty i przestrzenie nazw',
  'Organizacja typów w projekcie',
  'Adnotacje, asercje i operator satisfies',
  'Ewoluujące typy, struktury danych',
  'Typy globalne',
  'Ekosystem języka TypeScript',
  'Dokumentowanie typów i bibliotek',
  'Integracje z JS',
];

export const OPANUJ_TS_REACT_PRO_AGENDA = [
  'Praca z modułem React Pro',
  'Konfiguracja tsconfig.json',
  'Migracja do TS w istniejących projektach React.js',
  'Typowanie propsów',
  'Typowanie children',
  'Ekstrakcja propsów',
  'Typowanie event handlerów',
  'Komponenty generyczne',
  'useState',
  'useEffect',
  'useRef',
  'useMemo, useCallback',
  'Customowe hooki',
  'useReducer',
  'useContext',
  'Redux Tookit (RTK)',
  'Fetch API i Axios',
  'SWR i React Query',
  'Generowanie klientów HTTP z OpenAPI',
  'Render props',
  'Higher Order Components (HOC)',
  'Compound Components',
  'Zod i tRPC - bezpieczeństwo i spójność danych',
  'Wizualizacja danych',
  'Full-stack React z Astro',
  'Współpraca z AI w projektach z TypeScriptem i Reactem',
];

export const OPANUJ_AI_AGENDA = [
  'Zanim rozpoczniemy',
  'Pierwsze kroki współpracy z AI',
  'Pierwsze kroki z edytorem Cursor',
  'Programowanie z Cursorem',
  'Cursor Pro i rozszerzenia edytora',
  'Jak działają modele AI?',
  'Ocena wydajności modeli językowych',
  'Małe i duże modele językowe oraz fine-tuning',
  'Precyzyjność kluczem do sukcesu',
  'Anatomia skutecznego prompta',
  'Role Prompting',
  'In-context Learning',
  'Chain-of-Thought (CoT)',
  'Metoda sokratejska',
  'Ocena przez LLM - Samokrytyka',
  'Ocena przez LLM - Panel of Experts',
  'Integracje przez API',
  'Integracje no-code',
  'Modele językowe w środowisku lokalnym',
  'Nasze rekomendacje narzędzi',
];
