/**
 * Dane indeksu dokumentacji 10x Workflow (55 wpisow: strony, kroki, wezly,
 * lekcje, skille). Zrodlo prawdy dla strony docs (DocsBody.astro) i globalnej
 * palety wyszukiwania (TenxCosmicLayout.astro). `id` musi odpowiadac data-id
 * karty article.doc na stronie docs; wpisy lekcji nosza dodatkowo `url`
 * lekcji na platformie (/external/10xdevs-3/pl/NN).
 */

export interface DocEntry {
  /** Identyfikator wpisu - odpowiada data-id karty article.doc na stronie docs. */
  id: string;
  /** Typ wpisu (etykieta domenowa): strona, krok, lekcja, skill. */
  typ: 'strona' | 'krok' | 'lekcja' | 'skill';
  /** Rodzaj do filtra RODZAJ na stronie docs. */
  kind: 'strona' | 'koncept' | 'technika' | 'flow';
  /** Modul do filtra MODUL na stronie docs. */
  modul: 'CSC' | 'M1' | 'SKALOWANIE' | 'M3' | 'M4' | 'M5';
  tytul: string;
  streszczenie: string;
  tagi: string[];
  artefakt: string | null;
  /** Adres lekcji na platformie - tylko wpisy-lekcje. */
  url?: string;
}

/* DOCS: dopisuj nowe wpisy poniżej */
export const DOCS: DocEntry[] = [
{id:'csc',typ:'strona',kind:'strona',modul:'CSC',tytul:'Core Skills Chain (CSC) - strona modułu',streszczenie:'Rdzeń 10x Workflow: pięć skoków jednej jednostki pracy - new → research → plan → implement → review. Każdy krok zostawia artefakt na dysku.',tagi:['csc','workflow','łańcuch','moduł 2','landing'],artefakt:null},
{id:'k-new',typ:'krok',kind:'flow',modul:'CSC',tytul:'Krok 01: new - jedna jednostka pracy',streszczenie:'Pytanie: jedna jednostka pracy. Gwarancja: jasny, odwracalny zakres. Tnie zamiar na zmianę na tyle małą, że da się ją ogarnąć i cofnąć.',tagi:['krok 01','new','zakres','change.md','/10x-new'],artefakt:'change.md'},
{id:'k-research',typ:'krok',kind:'flow',modul:'CSC',tytul:'Krok 02: research - dowody do planu',streszczenie:'Pytanie: dowody do planu. Gwarancja: fakty zamiast założeń. Plan ma powstać na dowodach z repozytorium, nie na pamięci sprzed trzech refaktorów.',tagi:['krok 02','research','dowody','research.md','/10x-research'],artefakt:'research.md'},
{id:'k-plan',typ:'krok',kind:'flow',modul:'CSC',tytul:'Krok 03: plan - kluczowe decyzje deva',streszczenie:'Pytanie: kluczowe decyzje deva. Gwarancja: etapy + warunki sukcesu. Decyzje zapadają przed kodem, gdzie są tanie do zmiany.',tagi:['krok 03','plan','fazy','plan.md','/10x-plan'],artefakt:'plan.md'},
{id:'k-implement',typ:'krok',kind:'flow',modul:'CSC',tytul:'Krok 04: implement - implementacja etap po etapie',streszczenie:'Pytanie: implementacja etap po etapie. Gwarancja: commitowane, weryfikowalne kroki. Każda faza to punkt powrotu zamiast jednego wielkiego diffa.',tagi:['krok 04','implement','commity','progress','/10x-implement'],artefakt:'commity per faza'},
{id:'k-review',typ:'krok',kind:'flow',modul:'CSC',tytul:'Krok 05: review - czy implementacja realizuje plan?',streszczenie:'Pytanie: czy implementacja realizuje plan? Gwarancja: analiza subagentów: plan vs kod. Konkretny raport rozbieżności zamiast rytualnego „wygląda dobrze".',tagi:['krok 05','review','dryf','plan vs kod','/10x-impl-review'],artefakt:'raport review'},
{id:'s-new',typ:'skill',kind:'technika',modul:'CSC',tytul:'/10x-new',streszczenie:'Inicjalizuje folder zmiany context/changes/<change-id>/ z plikiem change.md - tożsamością jednostki pracy.',tagi:['skill','krok 01 · new','change.md'],artefakt:'change.md'},
{id:'s-research',typ:'skill',kind:'technika',modul:'CSC',tytul:'/10x-research',streszczenie:'Przeczesuje repozytorium równoległymi subagentami i składa wynik w research.md - kompletny obraz kodu pod plan.',tagi:['skill','krok 02 · research','subagenci'],artefakt:'research.md'},
{id:'s-plan',typ:'skill',kind:'technika',modul:'CSC',tytul:'/10x-plan',streszczenie:'Tworzy szczegółowy plan implementacji przez gruntowny research i iterację z człowiekiem: fazy, warunki sukcesu, sekcja Progress.',tagi:['skill','krok 03 · plan','fazy'],artefakt:'plan.md'},
{id:'s-implement',typ:'skill',kind:'technika',modul:'CSC',tytul:'/10x-implement',streszczenie:'Realizuje plan z context/changes/<change-id>/plan.md faza po fazie, z weryfikacją warunków sukcesu po każdej fazie.',tagi:['skill','krok 04 · implement','progress'],artefakt:'commity per faza'},
{id:'s-impl-review',typ:'skill',kind:'technika',modul:'CSC',tytul:'/10x-impl-review',streszczenie:'Recenzuje implementację względem planu: dryf, niebezpieczne decyzje, zgodność ze wzorcami repo.',tagi:['skill','krok 05 · review','dryf'],artefakt:'raport review'},
{id:'s-tdd',typ:'skill',kind:'technika',modul:'M3',tytul:'/10x-tdd',streszczenie:'Prowadzi zatwierdzony plan faza po fazie test-first, przez red → green → refactor - tylko fazy, które da się TDD-ować; resztę kieruje do /10x-implement.',tagi:['skill','lekcja q-02 · wyrocznia','krok 04 · implement','tdd','testy'],artefakt:'testy + kod'},
{id:'s-e2e',typ:'skill',kind:'technika',modul:'M3',tytul:'/10x-e2e',streszczenie:'Prowadzi przeglądarkowe (E2E) fazy planu na działającej aplikacji, ryzyko po ryzyku: plan → generacja → review → weryfikacja.',tagi:['skill','lekcja q-04 · e2e','krok 04 · implement','e2e','playwright'],artefakt:'testy E2E'},
{id:'s-goal-implement',typ:'skill',kind:'technika',modul:'SKALOWANIE',tytul:'/10x-goal-implement',streszczenie:'Autonomiczna realizacja planu pod /goal - bez człowieka między fazami; rodzeństwo /10x-implement do przebiegów nienadzorowanych i headless.',tagi:['skill','skalowanie','węzeł 02 · goal','autonomia'],artefakt:'commity + checklist'},
{id:'s-test-plan',typ:'skill',kind:'technika',modul:'M3',tytul:'/10x-test-plan',streszczenie:'Fazowy orkiestrator wdrażania testów w istniejącym produkcie: pisze test-plan.md i prowadzi każdą fazę rolloutu przez pełny łańcuch CSC.',tagi:['skill','lekcja q-01 · plan testów','testy','brownfield','orkiestrator'],artefakt:'test-plan.md'},
{id:'m1',typ:'strona',kind:'strona',modul:'M1',tytul:'Moduł 1: Fundament - strona modułu',streszczenie:'Pięć lekcji, które zamieniają mglisty pomysł w projekt gotowy do lotu: PRD, skille, bootstrap, onboarding agenta i pierwszy deploy. Rampa kończy się tam, gdzie startuje CSC.',tagi:['m1','fundament','moduł 1','landing','rampa startowa'],artefakt:null},
{id:'l-01',typ:'lekcja',kind:'koncept',modul:'M1',tytul:'Lekcja 01: Od pomysłu do PRD - co naprawdę budujemy?',streszczenie:'Pytanie: co naprawdę budujemy? Gwarancja: ustalenia, których kolejne prompty nie podważą. Sesja sokratejska /10x-shape, potem /10x-prd.',tagi:['lekcja 01','prd','shape','/10x-shape','/10x-prd'],artefakt:'shape-notes.md → prd.md',url:'/external/10xdevs-3/pl/01'},
{id:'l-02',typ:'lekcja',kind:'koncept',modul:'M1',tytul:'Lekcja 02: Od chatbota do Agenta - czym gra agent?',streszczenie:'Pytanie: czym gra agent? Gwarancja: powtarzalne narzędzia zamiast jednorazowych promptów. Skill to nie prompt - to odtwarzalna para kontraktów wejścia/wyjścia.',tagi:['lekcja 02','skille','metaprompting','agent'],artefakt:'skille z kontraktami',url:'/external/10xdevs-3/pl/02'},
{id:'l-03',typ:'lekcja',kind:'koncept',modul:'M1',tytul:'Lekcja 03: AI-Powered Bootstrap - na czym stawiamy?',streszczenie:'Pytanie: na czym stawiamy? Gwarancja: starter z oficjalnego CLI, nie boilerplate z generatora. Greenfield: tech-stack-selector → bootstrapper; brownfield: stack-assess → health-check.',tagi:['lekcja 03','bootstrap','stack','greenfield','brownfield'],artefakt:'tech-stack.md + scaffold',url:'/external/10xdevs-3/pl/03'},
{id:'l-04',typ:'lekcja',kind:'koncept',modul:'M1',tytul:'Lekcja 04: Agent Onboarding - co agent ma wiedzieć?',streszczenie:'Pytanie: co agent ma wiedzieć? Gwarancja: kontekst projektu bez szumu. Tylko to, czego model nie wywnioskuje z pretrainingu.',tagi:['lekcja 04','agents.md','onboarding','ai rules'],artefakt:'AGENTS.md',url:'/external/10xdevs-3/pl/04'},
{id:'l-05',typ:'lekcja',kind:'koncept',modul:'M1',tytul:'Lekcja 05: Z localhosta na produkcję - gdzie i jak wypływamy?',streszczenie:'Pytanie: gdzie i jak wypływamy? Gwarancja: działający deploy zamiast wiecznego localhosta. Kalkulacja przed skokiem: infra-research, roadmap, deployment.',tagi:['lekcja 05','deploy','produkcja','infrastruktura','roadmap'],artefakt:'infrastructure.md + roadmap.md + deploy',url:'/external/10xdevs-3/pl/05'},
{id:'s-shape',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-shape',streszczenie:'Prowadzi ustrukturyzowaną rozmowę odkrywczą, która zamienia pomysł - greenfield lub brownfield, wykrywane z repo - w shape-notes.md, wejście do /10x-prd.',tagi:['skill','lekcja 01','fundament','discovery'],artefakt:'shape-notes.md'},
{id:'s-prd',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-prd',streszczenie:'Generuje context/foundation/prd.md z shape-notes.md według zamkniętego schematu; sam trafia w szablon greenfield (10 sekcji) lub brownfield (11 sekcji).',tagi:['skill','lekcja 01','prd','fundament'],artefakt:'prd.md'},
{id:'s-tech-stack-selector',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-tech-stack-selector',streszczenie:'Wybiera starter i stack dla projektu greenfield po PRD: czyta prd.md, przechodzi rejestr starterów przez cztery bramki jakości i zapisuje tech-stack.md.',tagi:['skill','lekcja 03','stack','greenfield'],artefakt:'tech-stack.md'},
{id:'s-bootstrapper',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-bootstrapper',streszczenie:'Stawia scaffold w bieżącym katalogu po wyborze stacku: czyta tech-stack.md, uruchamia CLI oficjalnego startera i zapisuje log weryfikacji.',tagi:['skill','lekcja 03','bootstrap','cli'],artefakt:'scaffold + log'},
{id:'s-stack-assess',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-stack-assess',streszczenie:'Ocenia stack istniejącego projektu pod agenta według 4 bramek jakości; zapisuje stack-assessment.md z ocenami per komponent, lukami i gotowymi wpisami do CLAUDE.md/AGENTS.md.',tagi:['skill','lekcja 03','brownfield'],artefakt:'stack-assessment.md'},
{id:'s-health-check',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-health-check',streszczenie:'Audyt zdrowia istniejącego projektu: zależności, bezpieczeństwo, wykrycie test runnera, CI/CD i brakująca konfiguracja; kończy się werdyktem gotowości na agenta.',tagi:['skill','lekcja 03','brownfield','audyt'],artefakt:'health-check.md'},
{id:'s-agents-md',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-agents-md',streszczenie:'Generuje AGENTS.md - zwięzły przewodnik po repo dla agentów AI: konwencje, komendy, pułapki; krytyczne reguły na górze.',tagi:['skill','lekcja 04','onboarding','agents.md'],artefakt:'AGENTS.md'},
{id:'s-roadmap',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-roadmap',streszczenie:'Generuje roadmap.md z PRD jako uporządkowany zestaw pionowych wycinków end-to-end - kolejne widoczne dla użytkownika kamienie milowe do oddania w /10x-plan.',tagi:['skill','lekcja 05','roadmap','fundament'],artefakt:'roadmap.md'},
{id:'s-infra-research',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-infra-research',streszczenie:'Krótki wywiad plus równoległy research platform do deploymentu MVP, z kontrolą biasu źródeł; zapisuje infrastructure.md z punktowanym porównaniem i rejestrem ryzyk.',tagi:['skill','lekcja 05','infrastruktura','platforma'],artefakt:'infrastructure.md'},
{id:'s-deployment',typ:'skill',kind:'technika',modul:'M1',tytul:'/10x-deployment',streszczenie:'Bramka gotowości do deployu na PaaS (Cloudflare, Vercel, Netlify, Fly.io, Railway, Render): realny preflight, raport gotowości, natywna konfiguracja platformy, opcjonalny deploy z CLI.',tagi:['skill','lekcja 05','deploy','paas'],artefakt:'raport gotowości + config'},
{id:'skalowanie',typ:'strona',kind:'strona',modul:'SKALOWANIE',tytul:'Skalowanie (scale tier) - strona warstwy',streszczenie:'Warstwa nad łańcuchem: quality gates → goal → loops. Skalowanie to więcej cykli równolegle z bramkami jakości i autonomią - sufit przepustowości wyznacza Twoja zdolność do review.',tagi:['skalowanie','scale tier','quality gates','goal','loops','landing'],artefakt:null},
{id:'w-01',typ:'krok',kind:'koncept',modul:'SKALOWANIE',tytul:'Węzeł 01: quality gates - próba, której nie da się ominąć',streszczenie:'Pytanie: co pilnuje jakości, gdy Ciebie nie ma? Gwarancja: żadna faza nie przechodzi na czerwono. Lint i typecheck po każdej edycji, testy per faza, commit tylko na zielono.',tagi:['węzeł 01','quality gates','bramki','gom dżabbar','deliberate-break'],artefakt:'komplet zielonych bramek per faza'},
{id:'w-02',typ:'krok',kind:'flow',modul:'SKALOWANIE',tytul:'Węzeł 02: goal - plan wykonuje się bez autora',streszczenie:'Pytanie: jak plan wykonuje się bez Ciebie? Gwarancja: commit per faza na zielono albo uczciwy STOP. Autonomiczne przejście planu przez /10x-goal-implement pod /goal.',tagi:['węzeł 02','goal','autonomia','seldon','stop-blok','/10x-goal-implement'],artefakt:'commity per faza + run report'},
{id:'w-03',typ:'krok',kind:'flow',modul:'SKALOWANIE',tytul:'Węzeł 03: loops - więcej cykli równolegle',streszczenie:'Pytanie: ile cykli naraz udźwigniesz? Gwarancja: więcej przepustowości bez nierecenzowanego kodu. Równoległe cykle plan → implement → review z izolacją kontekstu; rytm zamiast na żądanie.',tagi:['węzeł 03','loops','równoległość','izolacja kontekstu','/loop'],artefakt:'osobny cykl per tor'},
{id:'m3',typ:'strona',kind:'strona',modul:'M3',tytul:'Moduł 3: Jakość - strona modułu',streszczenie:'Pięć lekcji o jakości: najpierw ryzyka, nie pliki - chroń najgroźniejsze scenariusze testem, którego asercja realnie pada. Jakość domyka blok 10xBuilder.',tagi:['m3','jakość','moduł 3','testy','landing'],artefakt:null},
{id:'q-01',typ:'lekcja',kind:'koncept',modul:'M3',tytul:'Lekcja 01: Plan testów - co zabija projekt najpierw?',streszczenie:'Pytanie: co zabija projekt najpierw? Gwarancja: najgroźniejsze scenariusze chronione najpierw. Mapa ryzyk wpływ × prawdopodobieństwo; ryzyko opisane jako awaria u usera.',tagi:['lekcja q-01','plan testów','mapa ryzyk','fremeni','/10x-test-plan'],artefakt:'test-plan.md',url:'/external/10xdevs-3/pl/11'},
{id:'q-02',typ:'lekcja',kind:'koncept',modul:'M3',tytul:'Lekcja 02: Od planu do testów - skąd test wie, co jest poprawne?',streszczenie:'Pytanie: skąd test wie, co jest poprawne? Gwarancja: asercja, która realnie pada na zepsutym kodzie. Wyrocznia z wymagań i researchu, nie z kodu; mutation check.',tagi:['lekcja q-02','wyrocznia','mutation','anti-patterny','/10x-tdd'],artefakt:'test chroniący ryzyko + czerwień',url:'/external/10xdevs-3/pl/12'},
{id:'q-03',typ:'lekcja',kind:'koncept',modul:'M3',tytul:'Lekcja 03: Hooki i triggery - co łapie błąd, zanim go zobaczysz?',streszczenie:'Pytanie: co łapie błąd, zanim go zobaczysz? Gwarancja: dryf wykryty sekundy po powstaniu, nie na końcu fazy. Warstwowa obrona według kosztu: per-edit → pre-commit → pre-push.',tagi:['lekcja q-03','hooki','tarcze','lint','typecheck'],artefakt:'hooki per-edit / pre-commit / pre-push',url:'/external/10xdevs-3/pl/13'},
{id:'q-04',typ:'lekcja',kind:'koncept',modul:'M3',tytul:'Lekcja 04: Testy E2E - czy całość naprawdę leci?',streszczenie:'Pytanie: czy całość naprawdę leci? Gwarancja: przelot end-to-end tam, gdzie unit by skłamał. Najtańszy test dający sygnał - E2E tylko tam, gdzie mock by skłamał; coverage nie jest celem.',tagi:['lekcja q-04','e2e','playwright','rocinante','seed test','/10x-e2e'],artefakt:'testy Playwright + seed test',url:'/external/10xdevs-3/pl/14'},
{id:'q-05',typ:'lekcja',kind:'koncept',modul:'M3',tytul:'Lekcja 05: Debugowanie - co mówią wszystkie przyrządy naraz?',streszczenie:'Pytanie: co mówią wszystkie przyrządy naraz? Gwarancja: diagnoza z dowodów, nie z przeczucia. Synteza dowodów z wielu źródeł: Sentry, wrangler logs, konsola i network z Playwrighta.',tagi:['lekcja q-05','debugowanie','sentry','pielgrzymi','wrangler','multi-source'],artefakt:'diagnoza + test przypinający naprawę',url:'/external/10xdevs-3/pl/15'},
{id:'m4',typ:'strona',kind:'strona',modul:'M4',tytul:'Moduł 4: Legacy - strona modułu (10xArchitect)',streszczenie:'Pięć lekcji o zastanym kodzie: decyzje architektoniczne z dowodów, nie z intuicji. Kręgosłup modułu: 5-elementowy raport architektoniczny - obronialny, nie przyjęty na wiarę.',tagi:['m4','legacy','10xarchitect','raport architektoniczny','landing'],artefakt:null},
{id:'a-01',typ:'lekcja',kind:'koncept',modul:'M4',tytul:'Lekcja 01: Skalowanie kontekstu - ile kontekstu naraz uniesie agent?',streszczenie:'Pytanie: ile kontekstu naraz uniesie agent? Gwarancja: kontekst racjonowany, nie wylewany. Nie „co agent ma wiedzieć?", tylko „co agent ma wiedzieć TERAZ?".',tagi:['lekcja a-01','kontekst','filtrfrak','agents.md','context/'],artefakt:'lean AGENTS.md + context/',url:'/external/10xdevs-3/pl/16'},
{id:'a-02',typ:'lekcja',kind:'koncept',modul:'M4',tytul:'Lekcja 02: Mapa projektu - jak wygląda teren, zanim wejdziesz?',streszczenie:'Pytanie: jak wygląda teren, zanim wejdziesz? Gwarancja: mapa z dowodów, nie z folderów. Szeroki skan: historia gita, wyszukiwania strukturalne, grafy zależności.',tagi:['lekcja a-02','mapa projektu','sondy','wide scan','git churn'],artefakt:'mapa projektu - pozycja ① raportu',url:'/external/10xdevs-3/pl/17'},
{id:'a-03',typ:'lekcja',kind:'koncept',modul:'M4',tytul:'Lekcja 03: Feature i hot spots - gdzie kod pęka najczęściej?',streszczenie:'Pytanie: gdzie kod pęka najczęściej? Gwarancja: ryzyko wskazane z dowodów, nie na wyczucie. Hot spot = złożoność × częstość zmian; semantykę domyka deterministyczne CLI.',tagi:['lekcja a-03','hot spots','ceres','ast-grep','change coupling','tornhill'],artefakt:'przegląd feature’a + hot spots',url:'/external/10xdevs-3/pl/18'},
{id:'a-04',typ:'lekcja',kind:'koncept',modul:'M4',tytul:'Lekcja 04: Refaktor odwracalny - jak przebudować bez zatrzymywania maszyny?',streszczenie:'Pytanie: jak przebudować bez zatrzymywania maszyny? Gwarancja: każdy krok odwracalny i osobno zielony. Strangler Fig, Branch by Abstraction, Mikado, ADR-y - zamiast big-bangu.',tagi:['lekcja a-04','refaktor','strangler fig','mikado','adr','fowler'],artefakt:'okazje refaktorowe + ADR-y',url:'/external/10xdevs-3/pl/19'},
{id:'a-05',typ:'lekcja',kind:'koncept',modul:'M4',tytul:'Lekcja 05: DDD z agentem - czy model mówi językiem domeny?',streszczenie:'Pytanie: czy model mówi językiem domeny? Gwarancja: granice i język, których zespół potrafi bronić. Event Storming, ubiquitous language, bounded contexts, inwarianty.',tagi:['lekcja a-05','ddd','event storming','bounded context','ubiquitous language','evans'],artefakt:'okazje DDD + glosariusz',url:'/external/10xdevs-3/pl/20'},
{id:'m5',typ:'strona',kind:'strona',modul:'M5',tytul:'Moduł 5: Teamwork - strona modułu (10xChampion)',streszczenie:'Pięć lekcji o pracy zespołowej z agentami: agent zarabia dla zespołu dopiero wtedy, gdy działa bez Ciebie. Artefakty AI to kod - jedno źródło prawdy, wersjonowanie, dystrybucja. Domyka kampanię.',tagi:['m5','teamwork','10xchampion','drużyna','landing'],artefakt:null},
{id:'t-01',typ:'lekcja',kind:'koncept',modul:'M5',tytul:'Lekcja 01: AI Internal Builders - co zbudować, a co kupić?',streszczenie:'Pytanie: co zbudować, a co kupić? Gwarancja: najmniejsze narzędzie, które zamyka realną lukę. Zostań przy SaaS tam, gdzie niesie odpowiedzialność platformową; buduj wokół lokalnej luki zespołu.',tagi:['lekcja t-01','build vs buy','pasiarze','helper'],artefakt:'wewnętrzny helper',url:'/external/10xdevs-3/pl/21'},
{id:'t-02',typ:'lekcja',kind:'koncept',modul:'M5',tytul:'Lekcja 02: Pierwszy agent zespołowy - z czego składa się agent, gdy zdejmiesz IDE?',streszczenie:'Pytanie: z czego składa się agent, gdy zdejmiesz IDE? Gwarancja: agent złożony świadomie, z licznikiem kosztów. Zejście poziom niżej, do prymitywów SDK; koszty i metryki od pierwszego dnia.',tagi:['lekcja t-02','sdk','drużyna','koszty','metryki'],artefakt:'pierwszy agent zespołowy + metryki kosztów',url:'/external/10xdevs-3/pl/22'},
{id:'t-03',typ:'lekcja',kind:'koncept',modul:'M5',tytul:'Lekcja 03: Code review w erze AI - kto pilnuje każdego PR, gdy śpisz?',streszczenie:'Pytanie: kto pilnuje każdego PR, gdy śpisz? Gwarancja: review na każdym PR, nie tylko gdy masz czas. Agent jako krok pipeline’u, uruchamiany bez Ciebie; severity × impact i triage.',tagi:['lekcja t-03','obserwator','ci/cd','pipeline','pr','/10x-impl-review-ci'],artefakt:'pipeline CI z komentarzem agenta na PR',url:'/external/10xdevs-3/pl/23'},
{id:'t-04',typ:'lekcja',kind:'koncept',modul:'M5',tytul:'Lekcja 04: Shared AI Registry - skąd zespół bierze wspólne skille?',streszczenie:'Pytanie: skąd zespół bierze wspólne skille? Gwarancja: jedna wersja prawdy zamiast dryfujących kopii. Artefakty AI to kod: jedno źródło prawdy, wersjonowanie, auth, dystrybucja.',tagi:['lekcja t-04','encyklopedia','rejestr','wersjonowanie','/10x-contract'],artefakt:'rejestr paczek: definicja + wydane wersje',url:'/external/10xdevs-3/pl/24'},
{id:'t-05',typ:'lekcja',kind:'koncept',modul:'M5',tytul:'Lekcja 05: Async i remote agents - jak delegować pracę na odległość?',streszczenie:'Pytanie: jak delegować pracę na odległość? Gwarancja: granice ustawione, zanim agent ruszy, kontrola wraca w review. Delegacja z odroczoną kontrolą: sandbox, granice sieci i sekretów przed startem.',tagi:['lekcja t-05','flota','async','sandbox','remote','monitoring'],artefakt:'zadanie delegowane zdalnie + raport w review',url:'/external/10xdevs-3/pl/25'},
{id:'s-impl-review-ci',typ:'skill',kind:'technika',modul:'M5',tytul:'/10x-impl-review-ci',streszczenie:'Uruchamia review implementacji nieinterakcyjnie w CI na PR: znajduje plan, sprawdza dryf, bezpieczeństwo, wzorce i pokrycie testami, commituje raport na branch PR i zostawia komentarz z podsumowaniem.',tagi:['skill','lekcja t-03 · review w ci','ci/cd','github actions','pr'],artefakt:'impl-review.md + komentarz na PR'},
{id:'s-contract',typ:'skill',kind:'technika',modul:'M5',tytul:'/10x-contract',streszczenie:'Rejestruje nośne nazwy i schematy (kontrakty) w docs/reference/contract-surfaces.md - powierzchnie, których zmiana łamie konsumentów w dole strumienia.',tagi:['skill','lekcja t-04 · registry','kontrakty','wersjonowanie'],artefakt:'contract-surfaces.md'},
];
