import type { PreworkPathQuizLanguageContent } from './types';

export const preworkPathQuizEn: PreworkPathQuizLanguageContent = {
  lessonTitles: {
    '02': '[1.2] Chatbot vs Agent vs Harness - definitions',
    '03': '[1.3] How to learn and grow with AI',
    '04': '[2.1] Agent in an IDE, Terminal, or Cloud?',
    '05': '[2.2] Cursor - Operational basics',
    '06': '[2.3] Claude Code - Operational basics',
    '07': '[2.4] Agent-Native IDE - the new generation of tools',
    '09': '[3.1] LLMs and their impact on everyday programming work',
    '10': '[3.2] Prompting patterns and anti-patterns',
    '11': '[3.3] Thread lifecycle and context management',
    '12': '[3.4] The language of working with AI in programming',
    '13': '[3.5] Recommended models and how to stay up to date',
    '14': '[4.1] Tech Stack Overview',
    '15': '[4.2] Good and bad course project',
    '16': '[4.3] Participant checklist and support (Circle)',
  },
  questions: [
    {
      id: 'foundations',
      type: 'single',
      title: 'Which distinction between a model, an agent, and a harness is correct?',
      options: [
        { value: 'correct', label: 'A model generates tokens, an agent completes work through tools, and a harness provides access, constraints, and working memory.' },
        { value: 'incorrect', label: 'Model, agent, and harness are three names for the same AI layer, mostly differing by user interface.' },
      ],
    },
    {
      id: 'learning',
      type: 'single',
      title: 'Which workflow better supports learning with AI?',
      options: [
        { value: 'correct', label: 'Generate a working solution first, then analyze explanations, trade-offs, and check-your-understanding questions.' },
        { value: 'incorrect', label: 'Accept working code as quickly as possible, because the final output is enough evidence of understanding.' },
      ],
    },
    {
      id: 'agentEnvironment',
      type: 'single',
      title: 'How do you evaluate your agent work environment choice?',
      options: [
        { value: 'experienced', label: 'I already work with an agent regularly and know my environment.' },
        { value: 'needs-choice', label: 'I want to choose between IDE, terminal, or cloud consciously.' },
      ],
    },
    {
      id: 'cursorIntro',
      type: 'single',
      title: 'Do you want an intro to working with Cursor?',
      options: [
        { value: 'yes', label: 'Yes, show me Cursor basics.' },
        { value: 'no', label: 'No, I do not need this lesson.' },
      ],
    },
    {
      id: 'claudeIntro',
      type: 'single',
      title: 'Do you want an intro to working with Claude Code in the terminal?',
      options: [
        { value: 'yes', label: 'Yes, show me Claude Code basics.' },
        { value: 'no', label: 'No, I do not need this lesson.' },
      ],
    },
    {
      id: 'llmBasics',
      type: 'single',
      title: 'Why can LLM-generated code look correct but still be wrong?',
      options: [
        { value: 'correct', label: 'The model predicts the most likely continuation of text, so it can reproduce a familiar pattern without validating the project semantics.' },
        { value: 'incorrect', label: 'If imports are valid and the formatter accepts the code, the LLM has usually validated the business logic too.' },
      ],
    },
    {
      id: 'promptPatterns',
      type: 'single',
      title: 'Which prompt is better for a reasoning model in a typical bug-fix task?',
      options: [
        { value: 'correct', label: '"Fix the double-discount bug. The tests in discount.test.ts must pass."' },
        { value: 'incorrect', label: '"First inspect the types, then trace the data flow, then identify the bug, and only then propose a fix."' },
      ],
    },
    {
      id: 'contextManagement',
      type: 'single',
      title: 'What is a good signal of context degradation in a long agent session?',
      options: [
        { value: 'correct', label: 'The agent repeats old decisions, invents paths, or ignores constraints that were already accepted.' },
        { value: 'incorrect', label: 'The agent asks one clarifying question before changing files.' },
      ],
    },
    {
      id: 'aiWorkLanguage',
      type: 'single',
      title: 'What is the default language policy for working with an agent in a codebase?',
      options: [
        { value: 'correct', label: 'Prefer English for operational prompts, project rules, and technical names; generate product copy in the user-facing language.' },
        { value: 'incorrect', label: 'Always prompt the agent in Polish because modern models reason equally well in every language and token cost does not matter.' },
      ],
    },
    {
      id: 'modelSelection',
      type: 'single',
      title: 'How should you choose models for agentic work?',
      options: [
        { value: 'correct', label: 'Match the model to the task: daily execution, a cheap mode for simple work, and a strong model for planning and hard decisions.' },
        { value: 'incorrect', label: 'Always pick the top model in one benchmark, because a leaderboard is enough for a production decision.' },
      ],
    },
    {
      id: 'stackKnown',
      type: 'single',
      title: 'What makes a stack more agent-friendly?',
      options: [
        { value: 'correct', label: 'Types, conventions, popular patterns in training data, and good documentation.' },
        { value: 'incorrect', label: 'Mainly novelty and few public examples, because then the agent mixes fewer patterns.' },
      ],
    },
  ],
  intro: {
    title: 'Quiz: build your prework path',
    description: 'Answer a few questions and we will show you the lessons and sections worth visiting before the course starts.',
    completedTitle: 'Your prework agenda',
    completedDescription: 'Your quiz result is saved. Review the recommended lessons and sections below.',
    start: 'Start quiz',
    savedResult: 'You have a saved quiz result.',
    submit: 'Show recommendations',
    retry: 'Take again',
    resultTitle: 'Your prework agenda',
    resultDescription: 'Recommendations are ordered by lesson sequence.',
    resultNavigationHint: 'Remember, you still have access to all prework lessons — if you want, you can simply jump to the second lesson.',
    goToNextLesson: 'Go to the second lesson',
    answersTitle: 'Your answers',
    answersDescription: 'Knowledge questions are marked as correct or incorrect. Preference questions show what you selected.',
    correctSelectedLabel: 'Your answer',
    correctAnswerLabel: 'Correct answer',
    selectedAnswerLabel: 'Your answer',
    openLesson: 'Open lesson',
    loading: 'Loading result...',
    saveWarning: 'We could not sync the result. It was saved locally in this browser.',
  },
  reasons: {
    alwaysEnvironment: 'This lesson gives you a shared map of agent work environments, regardless of tool choice.',
    alwaysAgentNative: 'Agent-native IDE is a fixed reference point for the new generation of tools.',
    alwaysProject: 'Every participant should see the criteria for a good and bad course project.',
    alwaysSupport: 'Every participant should know the startup checklist and support rules.',
    foundations: 'Your answer suggests the core AI work definitions are worth clarifying.',
    learning: 'Your answer suggests your AI learning mode is worth setting deliberately.',
    cursor: 'You chose an intro to Cursor as your agent work environment.',
    claude: 'You chose an intro to Claude Code and terminal-based work.',
    llmBasics: 'Your answer suggests a gap in understanding how LLMs affect everyday work.',
    promptPatterns: 'Your answer suggests prompting patterns are worth strengthening.',
    contextManagement: 'Your answer suggests context and thread management are worth improving.',
    aiWorkLanguage: 'Your answer suggests the language of working with agents is worth improving.',
    modelSelection: 'Your answer suggests model choice and benchmark interpretation are worth improving.',
    stack: 'Your answer suggests the agent-friendly stack overview is worth visiting.',
  },
};
