import type { PreworkPathQuizLanguageContent } from './types';

export const preworkPathQuizPl: PreworkPathQuizLanguageContent = {
  lessonTitles: {
    '02': '[1.2] Chatbot vs Agent vs Harness - definicje',
    '03': '[1.3] Jak uczyć się i rozwijać z AI',
    '04': '[2.1] Agent w IDE, Terminalu czy w Chmurze?',
    '05': '[2.2] Cursor - Podstawy operacyjne',
    '06': '[2.3] Claude Code - Podstawy operacyjne',
    '07': '[2.4] Agent-Native IDE - nowa generacja narzędzi',
    '09': '[3.1] LLMy i ich wpływ na codzienną pracę programisty',
    '10': '[3.2] Wzorce i antywzorce promptowania',
    '11': '[3.3] Cykl życia wątku i zarządzanie kontekstem',
    '12': '[3.4] Język pracy z AI w programowaniu',
    '13': '[3.5] Rekomendowane modele i jak być na bieżąco',
    '14': '[4.1] Tech Stack Overview',
    '15': '[4.2] Dobry i zły projekt kursowy',
    '16': '[4.3] Checklista uczestnika i support (Circle)',
  },
  questions: [
    {
      id: 'foundations',
      type: 'single',
      title: 'Które rozróżnienie modelu, agenta i harnessu jest poprawne?',
      options: [
        { value: 'correct', label: 'Model generuje kolejne tokeny, agent wykonuje zadanie przez narzędzia, a harness daje dostęp, ograniczenia i pamięć roboczą.' },
        { value: 'incorrect', label: 'Model, agent i harness to trzy nazwy tej samej warstwy AI, różniące się głównie interfejsem użytkownika.' },
      ],
    },
    {
      id: 'learning',
      type: 'single',
      title: 'Który workflow lepiej wspiera naukę z AI?',
      options: [
        { value: 'correct', label: 'Najpierw wygenerować rozwiązanie, potem przejść do wyjaśnień, trade-offów i pytań sprawdzających.' },
        { value: 'incorrect', label: 'Jak najszybciej zaakceptować działający kod, bo wynik końcowy jest wystarczającym dowodem zrozumienia.' },
      ],
    },
    {
      id: 'agentEnvironment',
      type: 'single',
      title: 'Czy masz preferowane środowisko pracy z AI w programowaniu?',
      options: [
        { value: 'experienced', label: 'Tak, pracuję z AI regularnie i mam preferowane środowisko.' },
        { value: 'needs-choice', label: 'Chcę lepiej rozumieć różnice między środowiskami.' },
      ],
    },
    {
      id: 'cursorIntro',
      type: 'single',
      title: 'Czy chcesz zapoznać się z podstawami edytora Cursor?',
      options: [
        { value: 'yes', label: 'Tak, chcę zobaczyć podstawy edytora Cursor.' },
        { value: 'no', label: 'Nie, nie potrzebuję tej lekcji.' },
      ],
    },
    {
      id: 'claudeIntro',
      type: 'single',
      title: 'Czy chcesz zapoznać się z podstawami narzędzia Claude Code?',
      options: [
        { value: 'yes', label: 'Tak, chcę zobaczyć podstawy Claude Code.' },
        { value: 'no', label: 'Nie, nie potrzebuję tej lekcji.' },
      ],
    },
    {
      id: 'llmBasics',
      type: 'single',
      title: 'Dlaczego kod wygenerowany przez LLM może wyglądać poprawnie, ale nadal być błędny?',
      options: [
        { value: 'correct', label: 'Model przewiduje najbardziej prawdopodobną kontynuację tekstu, więc może odtworzyć znany wzorzec bez prawdziwej walidacji semantyki projektu.' },
        { value: 'incorrect', label: 'Jeśli kod ma poprawne importy i przechodzi przez formatter, LLM zwykle zweryfikował też logikę biznesową.' },
      ],
    },
    {
      id: 'promptPatterns',
      type: 'single',
      title: 'Który prompt jest lepszy dla modelu rozumującego w typowym zadaniu naprawy błędu?',
      options: [
        { value: 'correct', label: '„Napraw błąd podwójnego naliczania rabatu. Testy w discount.test.ts muszą przechodzić.”' },
        { value: 'incorrect', label: '„Najpierw sprawdź typy, potem prześledź dane, potem wskaż błąd i dopiero zaproponuj poprawkę.”' },
      ],
    },
    {
      id: 'contextManagement',
      type: 'single',
      title: 'Co jest dobrym sygnałem degradacji kontekstu w długiej sesji z agentem?',
      options: [
        { value: 'correct', label: 'Agent powtarza stare ustalenia, wymyśla ścieżki albo ignoruje wcześniej zaakceptowane ograniczenia.' },
        { value: 'incorrect', label: 'Agent zadaje jedno pytanie doprecyzowujące przed zmianą plików.' },
      ],
    },
    {
      id: 'aiWorkLanguage',
      type: 'single',
      title: 'Jaka jest domyślna polityka językowa dla pracy z agentem w codebase?',
      options: [
        { value: 'correct', label: 'Polecenia operacyjne, reguły projektu i nazwy techniczne preferuj po angielsku, a copy produktu generuj w języku użytkownika.' },
        { value: 'incorrect', label: 'Zawsze pisz do agenta po polsku, bo nowoczesne modele rozumują tak samo dobrze w każdym języku i koszt tokenów nie ma znaczenia.' },
      ],
    },
    {
      id: 'modelSelection',
      type: 'single',
      title: 'Jak rozsądnie wybierać modele do pracy agentowej?',
      options: [
        { value: 'correct', label: 'Dobierz model do zadania: codzienna egzekucja, tani tryb do prostych zadań i mocny model do planowania oraz trudnych decyzji.' },
        { value: 'incorrect', label: 'Wybierz zawsze model z najwyższym miejscem w jednym benchmarku, bo ranking wystarcza jako decyzja produkcyjna.' },
      ],
    },
    {
      id: 'stackKnown',
      type: 'single',
      title: 'Co czyni stack bardziej „agent-friendly”?',
      options: [
        { value: 'correct', label: 'Typy, konwencje, popularne wzorce w danych treningowych i dobra dokumentacja.' },
        { value: 'incorrect', label: 'Głównie nowość technologii i mała liczba publicznych przykładów, bo agent wtedy mniej miesza wzorce.' },
      ],
    },
  ],
  intro: {
    title: 'Quiz: zbuduj swój prework',
    description: 'Odpowiedz na kilka pytań, a pokażemy ci lekcje i sekcje, które warto odwiedzić przed startem kursu.',
    completedTitle: 'Twoja agenda preworku',
    completedDescription: 'Twój wynik quizu jest zapisany. Poniżej znajdziesz rekomendowane lekcje i sekcje.',
    start: 'Rozwiąż quiz',
    savedResult: 'Masz zapisany wynik quizu.',
    submit: 'Pokaż rekomendacje',
    retry: 'Rozwiąż ponownie',
    resultTitle: 'Twoja agenda preworku',
    resultDescription: 'Rekomendacje są ułożone w kolejności lekcji.',
    resultNavigationHint: 'Pamiętaj, że wciąż masz dostęp do wszystkich lekcji preworku — jeśli chcesz, możesz po prostu przejść do drugiej lekcji.',
    goToNextLesson: 'Przejdź do drugiej lekcji',
    answersTitle: 'Twoje odpowiedzi',
    answersDescription: 'Pytania wiedzy oznaczamy jako poprawne lub błędne. Przy pytaniach preferencyjnych pokazujemy wybrany wariant.',
    correctSelectedLabel: 'Twoja odpowiedź',
    correctAnswerLabel: 'Poprawna odpowiedź',
    selectedAnswerLabel: 'Twoja odpowiedź',
    openLesson: 'Otwórz lekcję',
    loading: 'Ładowanie wyniku...',
    saveWarning: 'Nie udało się zsynchronizować wyniku. Zapisaliśmy go lokalnie w tej przeglądarce.',
  },
  reasons: {
    alwaysEnvironment: 'Ta lekcja daje wspólną mapę środowisk pracy z agentem, niezależnie od twojego wyboru narzędzia.',
    alwaysAgentNative: 'Agent-native IDE jest stałym punktem orientacyjnym dla nowej generacji narzędzi.',
    alwaysProject: 'Każdy uczestnik powinien zobaczyć kryteria dobrego i złego projektu kursowego.',
    alwaysSupport: 'Każdy uczestnik powinien znać checklistę startową i zasady supportu.',
    foundations: 'Odpowiedź sugeruje, że warto uporządkować podstawowe definicje pracy z AI.',
    learning: 'Odpowiedź sugeruje, że warto ustawić świadomy tryb uczenia się z AI.',
    cursor: 'Wybrałeś intro do Cursora jako środowiska pracy z agentem.',
    claude: 'Wybrałeś intro do Claude Code i pracy terminalowej.',
    llmBasics: 'Odpowiedź sugeruje lukę w rozumieniu wpływu LLMów na codzienną pracę.',
    promptPatterns: 'Odpowiedź sugeruje, że warto wzmocnić wzorce promptowania.',
    contextManagement: 'Odpowiedź sugeruje, że warto lepiej zarządzać kontekstem i wątkiem.',
    aiWorkLanguage: 'Odpowiedź sugeruje, że warto dopracować język pracy z agentem.',
    modelSelection: 'Odpowiedź sugeruje, że warto sprawniej wybierać modele i interpretować benchmarki.',
    stack: 'Odpowiedź sugeruje, że warto przejść overview stacku agent-friendly.',
  },
};
