import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { glob } from 'glob';
import { parseMarkdownLesson, type LessonFrontmatter } from './markdownLessonTransforms';
import { replaceMermaidWithCdnImages, replaceAssetsWithCdnUrls, injectPreworkLinks, PREWORK_BASE_URL } from './lessonHtmlPostProcessing';

export type LessonHtmlCourseKey =
  | 'lessons10xDevs3Pl'
  | 'lessons10xDevs3PreworkPl';

export interface LessonHtmlGenerationTarget {
  courseKey: LessonHtmlCourseKey;
  sourceGlob: string;
  outputDir: string;
  defaultLanguage?: 'pl' | 'en';
  requireLanguage: boolean;
  requireOrder: boolean;
  rootDir?: string;
  assetsPublicPath?: string;
}

export interface GeneratedLessonHtml {
  sourcePath: string;
  outputPath: string;
  html: string;
  lessonId: string;
  title: string;
  language?: 'pl' | 'en';
  order?: number;
}

export interface LessonHtmlCheckResult {
  ok: boolean;
  generated: GeneratedLessonHtml[];
  diagnostics: string[];
}

const GENERATED_MARKER = 'generated by generate-lesson-html';

function normalizePathForMetadata(filePath: string, rootDir: string): string {
  const relativePath = path.relative(rootDir, filePath);
  return relativePath.split(path.sep).join('/');
}

function escapeHtmlAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function getSourceHash(source: string): string {
  return createHash('sha256').update(source).digest('hex');
}

function isValidLanguage(language: unknown): language is 'pl' | 'en' {
  return language === 'pl' || language === 'en';
}

function validateLessonMetadata(
  sourcePath: string,
  frontmatter: LessonFrontmatter,
  target: LessonHtmlGenerationTarget
): {
  lessonId: string;
  language?: 'pl' | 'en';
  order?: number;
} {
  const lessonId = frontmatter.lessonId?.trim();
  if (!lessonId) {
    throw new Error(`Missing required lessonId in Markdown lesson: ${sourcePath}`);
  }

  const language = frontmatter.language ?? target.defaultLanguage;
  if (target.requireLanguage && !language) {
    throw new Error(`Missing required language in Markdown lesson: ${sourcePath}`);
  }

  if (language && !isValidLanguage(language)) {
    throw new Error(`Invalid language "${language}" in Markdown lesson: ${sourcePath}`);
  }

  if (target.requireOrder && (typeof frontmatter.order !== 'number' || !Number.isFinite(frontmatter.order))) {
    throw new Error(`Missing required numeric order in Markdown lesson: ${sourcePath}`);
  }

  return {
    lessonId,
    ...(language ? { language } : {}),
    ...(typeof frontmatter.order === 'number' ? { order: frontmatter.order } : {}),
  };
}

function getOutputPath(sourcePath: string, outputDir: string): string {
  const fileName = path.basename(sourcePath).replace(/\.md$/i, '.html');
  return path.join(outputDir, fileName);
}

export function createDefaultLessonHtmlGenerationTargets(
  rootDir = process.cwd()
): LessonHtmlGenerationTarget[] {
  return [
    {
      courseKey: 'lessons10xDevs3Pl',
      sourceGlob: path.join(rootDir, 'src/content-source/lessons10xDevs3/pl/*.md'),
      outputDir: path.join(rootDir, 'src/content/lessons10xDevs3/pl'),
      defaultLanguage: 'pl',
      requireLanguage: false,
      requireOrder: false,
      rootDir,
      assetsPublicPath: '/content/lessons10xDevs3/pl/assets',
    },
    {
      courseKey: 'lessons10xDevs3PreworkPl',
      sourceGlob: path.join(rootDir, 'src/content-source/lessons10xDevs3Prework/pl/*.md'),
      outputDir: path.join(rootDir, 'src/content/lessons10xDevs3Prework/pl'),
      defaultLanguage: 'pl',
      requireLanguage: true,
      requireOrder: true,
      rootDir,
    },
  ];
}

export function renderGeneratedLessonHtml({
  bodyHtml,
  courseKey,
  language,
  lessonId,
  order,
  sourceHash,
  sourcePath,
  title,
  titleEn,
}: {
  bodyHtml: string;
  courseKey: LessonHtmlCourseKey;
  language?: 'pl' | 'en';
  lessonId: string;
  order?: number;
  sourceHash: string;
  sourcePath: string;
  title: string;
  titleEn?: string;
}): string {
  const metaTags = [
    `<meta name="lesson-id" content="${escapeHtmlAttribute(title)}">`,
    titleEn ? `<meta name="title-en" content="${escapeHtmlAttribute(titleEn)}">` : null,
    `<meta name="source-path" content="${escapeHtmlAttribute(sourcePath)}">`,
    `<meta name="source-hash" content="${escapeHtmlAttribute(sourceHash)}">`,
    `<meta name="course-key" content="${escapeHtmlAttribute(courseKey)}">`,
    `<meta name="source" content="generated-html">`,
    `<meta name="canonical-lesson-id" content="${escapeHtmlAttribute(lessonId)}">`,
    language ? `<meta name="language" content="${escapeHtmlAttribute(language)}">` : null,
    typeof order === 'number' ? `<meta name="order" content="${order}">` : null,
  ].filter((tag): tag is string => tag !== null);

  return [
    `<!-- ${GENERATED_MARKER}; source: ${escapeHtmlAttribute(sourcePath)}; hash: ${escapeHtmlAttribute(sourceHash)} -->`,
    ...metaTags,
    '<html><head></head><body>',
    bodyHtml,
    '</body></html>',
    '',
  ].join('\n');
}

export async function generateLessonHtmlForSource(
  sourcePath: string,
  source: string,
  target: LessonHtmlGenerationTarget
): Promise<GeneratedLessonHtml | null> {
  const rootDir = target.rootDir ?? process.cwd();
  const parsedLesson = await parseMarkdownLesson(sourcePath, source);

  if (parsedLesson.frontmatter.hidden) {
    return null;
  }

  const metadata = validateLessonMetadata(sourcePath, parsedLesson.frontmatter, target);
  const relativeSourcePath = normalizePathForMetadata(sourcePath, rootDir);
  const sourceHash = getSourceHash(source);

  let bodyHtml = parsedLesson.bodyHtml;
  if (target.assetsPublicPath) {
    bodyHtml = bodyHtml.replace(/src="\.\/assets\//g, `src="${target.assetsPublicPath}/`);
  }
  bodyHtml = replaceAssetsWithCdnUrls(bodyHtml);
  bodyHtml = replaceMermaidWithCdnImages(bodyHtml);
  bodyHtml = injectPreworkLinks(bodyHtml, target.defaultLanguage ?? 'pl', PREWORK_BASE_URL);

  const html = renderGeneratedLessonHtml({
    bodyHtml,
    courseKey: target.courseKey,
    language: metadata.language,
    lessonId: metadata.lessonId,
    order: metadata.order,
    sourceHash,
    sourcePath: relativeSourcePath,
    title: parsedLesson.title,
    titleEn: parsedLesson.frontmatter.titleEn,
  });

  return {
    sourcePath,
    outputPath: getOutputPath(sourcePath, target.outputDir),
    html,
    lessonId: metadata.lessonId,
    title: parsedLesson.title,
    ...(metadata.language ? { language: metadata.language } : {}),
    ...(typeof metadata.order === 'number' ? { order: metadata.order } : {}),
  };
}

export async function generateLessonHtmlForTargets(
  targets: LessonHtmlGenerationTarget[]
): Promise<GeneratedLessonHtml[]> {
  const generated: GeneratedLessonHtml[] = [];

  for (const target of targets) {
    const sourceFiles = await glob(target.sourceGlob, { nodir: true });

    for (const sourcePath of sourceFiles.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))) {
      const source = await readFile(sourcePath, 'utf-8');
      const generatedLesson = await generateLessonHtmlForSource(sourcePath, source, target);

      if (generatedLesson) {
        generated.push(generatedLesson);
      }
    }
  }

  assertUniqueOutputPaths(generated);

  return generated.sort((a, b) => a.outputPath.localeCompare(b.outputPath, undefined, { numeric: true }));
}

function assertUniqueOutputPaths(generated: GeneratedLessonHtml[]): void {
  const seen = new Map<string, string>();

  for (const lesson of generated) {
    const previousSource = seen.get(lesson.outputPath);
    if (previousSource) {
      throw new Error(
        `Duplicate generated lesson output "${lesson.outputPath}" from "${previousSource}" and "${lesson.sourcePath}"`
      );
    }

    seen.set(lesson.outputPath, lesson.sourcePath);
  }
}

async function listGeneratedLookingHtmlFiles(dir: string): Promise<string[]> {
  let entries: string[];

  try {
    entries = await readdir(dir);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return [];
    }

    throw error;
  }

  const generatedFiles: string[] = [];
  for (const entry of entries) {
    if (!entry.endsWith('.html')) {
      continue;
    }

    const filePath = path.join(dir, entry);
    const content = await readFile(filePath, 'utf-8');
    if (content.includes(GENERATED_MARKER)) {
      generatedFiles.push(filePath);
    }
  }

  return generatedFiles;
}

export async function writeGeneratedLessonHtml(
  targets: LessonHtmlGenerationTarget[]
): Promise<GeneratedLessonHtml[]> {
  const generated = await generateLessonHtmlForTargets(targets);

  for (const lesson of generated) {
    await mkdir(path.dirname(lesson.outputPath), { recursive: true });
    await writeFile(lesson.outputPath, lesson.html, 'utf-8');
  }

  const rootDir = targets[0]?.rootDir ?? process.cwd();
  for (const target of targets) {
    if (!target.assetsPublicPath) continue;

    const contentAssetsDir = path.join(target.outputDir, 'assets');
    if (!existsSync(contentAssetsDir)) continue;

    const publicAssetsDir = path.join(rootDir, 'public', target.assetsPublicPath);
    await cp(contentAssetsDir, publicAssetsDir, { recursive: true });
  }

  return generated;
}

export async function checkGeneratedLessonHtml(
  targets: LessonHtmlGenerationTarget[]
): Promise<LessonHtmlCheckResult> {
  const generated = await generateLessonHtmlForTargets(targets);
  const diagnostics: string[] = [];
  const expectedPaths = new Set(generated.map((lesson) => lesson.outputPath));

  for (const lesson of generated) {
    let existing: string;

    try {
      existing = await readFile(lesson.outputPath, 'utf-8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        diagnostics.push(`Missing generated HTML: ${lesson.outputPath}`);
        continue;
      }

      throw error;
    }

    if (existing !== lesson.html) {
      diagnostics.push(`Stale generated HTML: ${lesson.outputPath}`);
    }
  }

  for (const target of targets) {
    const generatedLookingFiles = await listGeneratedLookingHtmlFiles(target.outputDir);
    for (const filePath of generatedLookingFiles) {
      if (!expectedPaths.has(filePath)) {
        diagnostics.push(`Extra generated HTML without source: ${filePath}`);
      }
    }
  }

  return {
    ok: diagnostics.length === 0,
    generated,
    diagnostics,
  };
}

export const __testUtils = {
  GENERATED_MARKER,
  escapeHtmlAttribute,
  getOutputPath,
};
