import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { glob } from 'glob';
import { parseFrontmatter, type LessonFrontmatter } from './markdownLessonTransforms';

export type LessonHtmlEnrichmentLanguage = 'en';
export type EnrichedLessonHtmlCourseKey = 'lessons10xDevs3PreworkEn' | 'lessons10xDevs3En';

export interface LessonHtmlEnrichmentTarget {
  courseKey: EnrichedLessonHtmlCourseKey;
  language: LessonHtmlEnrichmentLanguage;
  sourceGlob: string;
  htmlDir: string;
  rootDir?: string;
}

export interface EnrichedLessonHtml {
  sourcePath: string;
  outputPath: string;
  html: string;
  lessonId: string;
  displayLessonId: string;
  language: LessonHtmlEnrichmentLanguage;
  order: number;
}

export interface LessonHtmlEnrichmentCheckResult {
  ok: boolean;
  enriched: EnrichedLessonHtml[];
  diagnostics: string[];
}

const ENRICHED_MARKER = 'enriched by enrich-lesson-html';
const GENERATED_MARKER = 'generated by generate-lesson-html';
const MANAGED_META_NAMES = [
  'lesson-id',
  'source-path',
  'source-hash',
  'metadata-source-path',
  'metadata-source-hash',
  'course-key',
  'source',
  'canonical-lesson-id',
  'language',
  'order',
] as const;

function normalizePathForMetadata(filePath: string, rootDir: string): string {
  const relativePath = path.relative(rootDir, filePath);
  return relativePath.split(path.sep).join('/');
}

function escapeHtmlAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function getHash(source: string): string {
  return createHash('sha256').update(source).digest('hex');
}

function getLessonFilePrefix(sourcePath: string): string {
  return path.basename(sourcePath).replace(/\.md$/i, '').split('_')[0];
}

async function findTranslatedHtmlPath(htmlDir: string, sourcePath: string): Promise<string> {
  const lessonFilePrefix = getLessonFilePrefix(sourcePath);
  const htmlFiles = await listHtmlFiles(htmlDir);
  const matchingFiles = htmlFiles.filter((filePath) => {
    const fileName = path.basename(filePath);
    return fileName === `${lessonFilePrefix}.html` || fileName.startsWith(`${lessonFilePrefix}_`);
  });

  if (matchingFiles.length === 0) {
    throw new Error(`Missing translated HTML with prefix ${lessonFilePrefix}: ${htmlDir}`);
  }

  if (matchingFiles.length > 1) {
    throw new Error(
      `Multiple translated HTML files with prefix ${lessonFilePrefix}: ${matchingFiles.join(', ')}`
    );
  }

  return matchingFiles[0];
}

function validateSourceMetadata(
  sourcePath: string,
  frontmatter: LessonFrontmatter
): {
  lessonId: string;
  displayLessonId: string;
  order: number;
} {
  const lessonId = frontmatter.lessonId?.trim();
  if (!lessonId) {
    throw new Error(`Missing required lessonId in Markdown lesson: ${sourcePath}`);
  }

  if (frontmatter.language !== 'pl') {
    throw new Error(`Expected Polish source language "pl" in Markdown lesson: ${sourcePath}`);
  }

  const displayLessonId = frontmatter.titleEn?.trim();
  if (!displayLessonId) {
    throw new Error(`Missing required titleEn in Markdown lesson: ${sourcePath}`);
  }

  if (typeof frontmatter.order !== 'number' || !Number.isFinite(frontmatter.order)) {
    throw new Error(`Missing required numeric order in Markdown lesson: ${sourcePath}`);
  }

  return {
    lessonId,
    displayLessonId,
    order: frontmatter.order,
  };
}

function removeManagedMetadata(html: string): string {
  let cleaned = html.replace(new RegExp(`<!--\\s*${ENRICHED_MARKER}[^>]*-->\\s*`, 'gi'), '');
  cleaned = cleaned.replace(new RegExp(`<!--\\s*${GENERATED_MARKER}[^>]*-->\\s*`, 'gi'), '');

  for (const name of MANAGED_META_NAMES) {
    const metaPattern = new RegExp(`<meta\\b(?=[^>]*\\bname=["']${name}["'])[^>]*>\\s*`, 'gi');
    cleaned = cleaned.replace(metaPattern, '');
  }

  return cleaned.trimStart();
}

function localizeInternalExternalLessonLinks(html: string, language: LessonHtmlEnrichmentLanguage): string {
  return html.replace(
    /(\bhref\s*=\s*["'])\/external\/(10xdevs-3(?:-prework)?)\/(?:pl|en)(?=\/|[#?]|["'])/gi,
    `$1/external/$2/${language}`
  );
}

export function renderEnrichedLessonHtml({
  bodyHtml,
  courseKey,
  displayLessonId,
  language,
  lessonId,
  metadataSourceHash,
  metadataSourcePath,
  order,
}: {
  bodyHtml: string;
  courseKey: EnrichedLessonHtmlCourseKey;
  displayLessonId: string;
  language: LessonHtmlEnrichmentLanguage;
  lessonId: string;
  metadataSourceHash: string;
  metadataSourcePath: string;
  order: number;
}): string {
  const metaTags = [
    `<meta name="lesson-id" content="${escapeHtmlAttribute(displayLessonId)}">`,
    `<meta name="metadata-source-path" content="${escapeHtmlAttribute(metadataSourcePath)}">`,
    `<meta name="metadata-source-hash" content="${escapeHtmlAttribute(metadataSourceHash)}">`,
    `<meta name="course-key" content="${escapeHtmlAttribute(courseKey)}">`,
    `<meta name="source" content="translation-html">`,
    `<meta name="canonical-lesson-id" content="${escapeHtmlAttribute(lessonId)}">`,
    `<meta name="language" content="${escapeHtmlAttribute(language)}">`,
    `<meta name="order" content="${order}">`,
  ];

  return [
    `<!-- ${ENRICHED_MARKER}; metadata-source: ${escapeHtmlAttribute(metadataSourcePath)}; hash: ${escapeHtmlAttribute(metadataSourceHash)} -->`,
    ...metaTags,
    localizeInternalExternalLessonLinks(removeManagedMetadata(bodyHtml), language).trimEnd(),
    '',
  ].join('\n');
}

export function createDefaultLessonHtmlEnrichmentTargets(
  rootDir = process.cwd(),
  language: LessonHtmlEnrichmentLanguage = 'en'
): LessonHtmlEnrichmentTarget[] {
  if (language !== 'en') {
    throw new Error(`Unsupported lesson HTML enrichment language: ${language}`);
  }

  return [
    {
      courseKey: 'lessons10xDevs3PreworkEn',
      language,
      sourceGlob: path.join(rootDir, 'src/content-source/lessons10xDevs3Prework/pl/*.md'),
      htmlDir: path.join(rootDir, 'src/content/lessons10xDevs3Prework/en'),
      rootDir,
    },
    {
      courseKey: 'lessons10xDevs3En',
      language,
      sourceGlob: path.join(rootDir, 'src/content-source/lessons10xDevs3/pl/*.md'),
      htmlDir: path.join(rootDir, 'src/content/lessons10xDevs3/en'),
      rootDir,
    },
  ];
}

export async function enrichLessonHtmlForTargets(
  targets: LessonHtmlEnrichmentTarget[]
): Promise<EnrichedLessonHtml[]> {
  const enriched: EnrichedLessonHtml[] = [];

  for (const target of targets) {
    const rootDir = target.rootDir ?? process.cwd();
    const htmlFiles = await listHtmlFiles(target.htmlDir);
    if (htmlFiles.length === 0) {
      continue;
    }

    const sourceFiles = await glob(target.sourceGlob, { nodir: true });

    for (const sourcePath of sourceFiles.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))) {
      const source = await readFile(sourcePath, 'utf-8');
      const frontmatter = parseFrontmatter(source).data;

      if (frontmatter.hidden) {
        continue;
      }

      const { lessonId, displayLessonId, order } = validateSourceMetadata(sourcePath, frontmatter);
      const outputPath = await findTranslatedHtmlPath(target.htmlDir, sourcePath);
      let existingHtml: string;

      try {
        existingHtml = await readFile(outputPath, 'utf-8');
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
          throw new Error(`Missing translated HTML: ${outputPath}`);
        }

        throw error;
      }

      const metadataSourcePath = normalizePathForMetadata(sourcePath, rootDir);
      const metadataSourceHash = getHash(source);

      enriched.push({
        sourcePath,
        outputPath,
        html: renderEnrichedLessonHtml({
          bodyHtml: existingHtml,
          courseKey: target.courseKey,
          displayLessonId,
          language: target.language,
          lessonId,
          metadataSourceHash,
          metadataSourcePath,
          order,
        }),
        lessonId,
        displayLessonId,
        language: target.language,
        order,
      });
    }
  }

  return enriched.sort((a, b) => a.outputPath.localeCompare(b.outputPath, undefined, { numeric: true }));
}

export async function writeEnrichedLessonHtml(
  targets: LessonHtmlEnrichmentTarget[]
): Promise<EnrichedLessonHtml[]> {
  const enriched = await enrichLessonHtmlForTargets(targets);

  for (const lesson of enriched) {
    await mkdir(path.dirname(lesson.outputPath), { recursive: true });
    await writeFile(lesson.outputPath, lesson.html, 'utf-8');
  }

  return enriched;
}

async function listHtmlFiles(dir: string): Promise<string[]> {
  let entries: string[];

  try {
    entries = await readdir(dir);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return [];
    }

    throw error;
  }

  return entries.filter((entry) => entry.endsWith('.html')).map((entry) => path.join(dir, entry));
}

export async function checkEnrichedLessonHtml(
  targets: LessonHtmlEnrichmentTarget[]
): Promise<LessonHtmlEnrichmentCheckResult> {
  const diagnostics: string[] = [];
  let enriched: EnrichedLessonHtml[] = [];

  try {
    enriched = await enrichLessonHtmlForTargets(targets);
  } catch (error) {
    diagnostics.push((error as Error).message);
    return {
      ok: false,
      enriched: [],
      diagnostics,
    };
  }

  const expectedPaths = new Set(enriched.map((lesson) => lesson.outputPath));

  for (const lesson of enriched) {
    let existing: string;

    try {
      existing = await readFile(lesson.outputPath, 'utf-8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        diagnostics.push(`Missing translated HTML: ${lesson.outputPath}`);
        continue;
      }

      throw error;
    }

    if (existing !== lesson.html) {
      diagnostics.push(`Stale enriched HTML metadata: ${lesson.outputPath}`);
    }
  }

  for (const target of targets) {
    const htmlFiles = await listHtmlFiles(target.htmlDir);
    for (const filePath of htmlFiles) {
      if (!expectedPaths.has(filePath)) {
        diagnostics.push(`Extra translated HTML without source: ${filePath}`);
      }
    }
  }

  return {
    ok: diagnostics.length === 0,
    enriched,
    diagnostics,
  };
}

export const __testUtils = {
  ENRICHED_MARKER,
  localizeInternalExternalLessonLinks,
  removeManagedMetadata,
};
