/* @vitest-environment jsdom */

import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  checkGeneratedLessonHtml,
  createDefaultLessonHtmlGenerationTargets,
  generateLessonHtmlForSource,
  generateLessonHtmlForTargets,
  type LessonHtmlGenerationTarget,
  renderGeneratedLessonHtml,
  writeGeneratedLessonHtml,
} from './lessonHtmlGenerator';

const tempDirs: string[] = [];

async function createTempDir(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'lesson-html-generator-'));
  tempDirs.push(dir);
  return dir;
}

async function writeFixture(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf-8');
}

function createTarget(rootDir: string, sourceGlob: string, outputDir: string): LessonHtmlGenerationTarget {
  return {
    courseKey: 'lessons10xDevs3PreworkPl',
    sourceGlob,
    outputDir,
    defaultLanguage: 'pl',
    requireLanguage: true,
    requireOrder: true,
    rootDir,
  };
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((dir) => fs.rm(dir, { recursive: true, force: true })));
});

describe('generateLessonHtmlForSource', () => {
  it('maps frontmatter metadata into legacy-compatible HTML meta tags', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, 'src/content-source/lessons10xDevs3Prework/pl/01-test.md');
    const target = createTarget(rootDir, `${path.dirname(sourcePath)}/*.md`, path.join(rootDir, 'src/content/out'));

    const generated = await generateLessonHtmlForSource(
      sourcePath,
      `---
title: "[1.1] Test lesson"
titleEn: "[1.1] Test lesson EN"
lessonId: "01"
language: "pl"
order: 1
---

# Test lesson

Body`,
      target
    );

    expect(generated).toMatchObject({
      outputPath: path.join(rootDir, 'src/content/out/01-test.html'),
      lessonId: '01',
      language: 'pl',
      order: 1,
      title: '[1.1] Test lesson',
    });
    expect(generated?.html).toContain('generated by generate-lesson-html');
    expect(generated?.html).toContain('<meta name="lesson-id" content="[1.1] Test lesson">');
    expect(generated?.html).toContain('<meta name="title-en" content="[1.1] Test lesson EN">');
    expect(generated?.html).toContain('<meta name="canonical-lesson-id" content="01">');
    expect(generated?.html).toContain('<meta name="language" content="pl">');
    expect(generated?.html).toContain('<meta name="order" content="1">');
    expect(generated?.html).toContain('<p>Body</p>');
  });

  it('escapes metadata attributes', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, '01-test.md');
    const target = createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out'));

    const generated = await generateLessonHtmlForSource(
      sourcePath,
      `---
title: "A & \\"quoted\\" <title>"
lessonId: "01"
language: "pl"
order: 1
---

# Test`,
      target
    );

    expect(generated?.html).toContain('<meta name="lesson-id" content="A &amp; &quot;quoted&quot; &lt;title&gt;">');
  });

  it('skips hidden lessons', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, '00-meta.md');
    const target = createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out'));

    const generated = await generateLessonHtmlForSource(
      sourcePath,
      `---
hidden: true
---

# Editorial notes`,
      target
    );

    expect(generated).toBeNull();
  });

  it('fails when required lessonId is missing', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, 'missing-id.md');
    const target = createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out'));

    await expect(
      generateLessonHtmlForSource(
        sourcePath,
        `---
title: "Missing ID"
language: "pl"
order: 1
---

# Missing ID`,
        target
      )
    ).rejects.toThrow(/Missing required lessonId/);
  });

  it('fails when required language is missing', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, 'missing-language.md');
    const target = {
      ...createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out')),
      defaultLanguage: undefined,
    };

    await expect(
      generateLessonHtmlForSource(
        sourcePath,
        `---
title: "Missing language"
lessonId: "01"
order: 1
---

# Missing language`,
        target
      )
    ).rejects.toThrow(/Missing required language/);
  });

  it('fails when language is invalid', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, 'invalid-language.md');
    const target = createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out'));

    await expect(
      generateLessonHtmlForSource(
        sourcePath,
        `---
title: "Invalid language"
lessonId: "01"
language: "de"
order: 1
---

# Invalid language`,
        target
      )
    ).rejects.toThrow(/Invalid language "de"/);
  });

  it('fails when required order is missing', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, 'missing-order.md');
    const target = createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out'));

    await expect(
      generateLessonHtmlForSource(
        sourcePath,
        `---
title: "Missing order"
lessonId: "01"
language: "pl"
---

# Missing order`,
        target
      )
    ).rejects.toThrow(/Missing required numeric order/);
  });

  it('adds the mermaid class to generated HTML', async () => {
    const rootDir = await createTempDir();
    const sourcePath = path.join(rootDir, '01-mermaid.md');
    const target = createTarget(rootDir, `${rootDir}/*.md`, path.join(rootDir, 'out'));

    const generated = await generateLessonHtmlForSource(
      sourcePath,
      `---
title: "Mermaid"
lessonId: "01"
language: "pl"
order: 1
---

\`\`\`mermaid
graph TD;
  A-->B;
\`\`\`
`,
      target
    );

    expect(generated?.html).toContain('<pre class="mermaid" data-language="mermaid">');
  });
});

describe('createDefaultLessonHtmlGenerationTargets', () => {
  it('does not generate English prework HTML from Markdown', () => {
    const targets = createDefaultLessonHtmlGenerationTargets('/repo');

    expect(targets.map((target) => target.courseKey)).toEqual([
      'lessons10xDevs3Pl',
      'lessons10xDevs3PreworkPl',
    ]);
    expect(targets.map((target) => target.sourceGlob)).not.toContain(
      '/repo/src/content-source/lessons10xDevs3Prework/en/*.md'
    );
  });
});

describe('generateLessonHtmlForTargets', () => {
  it('generates sorted output and preserves source basename with html extension', async () => {
    const rootDir = await createTempDir();
    const sourceDir = path.join(rootDir, 'src');
    const outputDir = path.join(rootDir, 'out');
    await writeFixture(
      path.join(sourceDir, '02-second.md'),
      `---
title: "Second"
lessonId: "02"
language: "pl"
order: 2
---

# Second`
    );
    await writeFixture(
      path.join(sourceDir, '01-first.md'),
      `---
title: "First"
lessonId: "01"
language: "pl"
order: 1
---

# First`
    );

    const generated = await generateLessonHtmlForTargets([
      createTarget(rootDir, `${sourceDir}/*.md`, outputDir),
    ]);

    expect(generated.map((lesson) => path.basename(lesson.outputPath))).toEqual([
      '01-first.html',
      '02-second.html',
    ]);
  });

  it('fails on duplicate output paths across targets', async () => {
    const rootDir = await createTempDir();
    const sourceA = path.join(rootDir, 'a');
    const sourceB = path.join(rootDir, 'b');
    const outputDir = path.join(rootDir, 'out');
    const lesson = `---
title: "Duplicate"
lessonId: "01"
language: "pl"
order: 1
---

# Duplicate`;
    await writeFixture(path.join(sourceA, '01-duplicate.md'), lesson);
    await writeFixture(path.join(sourceB, '01-duplicate.md'), lesson);

    await expect(
      generateLessonHtmlForTargets([
        createTarget(rootDir, `${sourceA}/*.md`, outputDir),
        createTarget(rootDir, `${sourceB}/*.md`, outputDir),
      ])
    ).rejects.toThrow(/Duplicate generated lesson output/);
  });
});

describe('writeGeneratedLessonHtml and checkGeneratedLessonHtml', () => {
  it('writes generated HTML and passes check mode immediately after generation', async () => {
    const rootDir = await createTempDir();
    const sourceDir = path.join(rootDir, 'src');
    const outputDir = path.join(rootDir, 'out');
    await writeFixture(
      path.join(sourceDir, '01-test.md'),
      `---
title: "Test"
lessonId: "01"
language: "pl"
order: 1
---

# Test`
    );
    const target = createTarget(rootDir, `${sourceDir}/*.md`, outputDir);

    const written = await writeGeneratedLessonHtml([target]);
    const check = await checkGeneratedLessonHtml([target]);

    expect(written).toHaveLength(1);
    await expect(fs.readFile(path.join(outputDir, '01-test.html'), 'utf-8')).resolves.toContain(
      'generated by generate-lesson-html'
    );
    expect(check).toMatchObject({
      ok: true,
      diagnostics: [],
    });
  });

  it('detects stale generated HTML', async () => {
    const rootDir = await createTempDir();
    const sourceDir = path.join(rootDir, 'src');
    const outputDir = path.join(rootDir, 'out');
    await writeFixture(
      path.join(sourceDir, '01-test.md'),
      `---
title: "Test"
lessonId: "01"
language: "pl"
order: 1
---

# Test`
    );
    const target = createTarget(rootDir, `${sourceDir}/*.md`, outputDir);

    await writeGeneratedLessonHtml([target]);
    await fs.appendFile(path.join(outputDir, '01-test.html'), '\nmanual edit', 'utf-8');

    const check = await checkGeneratedLessonHtml([target]);

    expect(check.ok).toBe(false);
    expect(check.diagnostics).toEqual([expect.stringContaining('Stale generated HTML')]);
  });

  it('detects missing generated HTML', async () => {
    const rootDir = await createTempDir();
    const sourceDir = path.join(rootDir, 'src');
    const outputDir = path.join(rootDir, 'out');
    await writeFixture(
      path.join(sourceDir, '01-test.md'),
      `---
title: "Test"
lessonId: "01"
language: "pl"
order: 1
---

# Test`
    );

    const check = await checkGeneratedLessonHtml([
      createTarget(rootDir, `${sourceDir}/*.md`, outputDir),
    ]);

    expect(check.ok).toBe(false);
    expect(check.diagnostics).toEqual([expect.stringContaining('Missing generated HTML')]);
  });

  it('detects extra generated-looking HTML without source', async () => {
    const rootDir = await createTempDir();
    const sourceDir = path.join(rootDir, 'src');
    const outputDir = path.join(rootDir, 'out');
    await fs.mkdir(outputDir, { recursive: true });
    await fs.writeFile(
      path.join(outputDir, '99-extra.html'),
      '<!-- generated by generate-lesson-html; source: old.md; hash: old -->\n<p>old</p>',
      'utf-8'
    );

    const check = await checkGeneratedLessonHtml([
      createTarget(rootDir, `${sourceDir}/*.md`, outputDir),
    ]);

    expect(check.ok).toBe(false);
    expect(check.diagnostics).toEqual([expect.stringContaining('Extra generated HTML without source')]);
  });
});

describe('renderGeneratedLessonHtml', () => {
  it('does not include timestamp metadata', () => {
    const html = renderGeneratedLessonHtml({
      bodyHtml: '<p>Body</p>',
      courseKey: 'lessons10xDevs3Pl',
      lessonId: '01',
      sourceHash: 'abc123',
      sourcePath: 'src/content-source/lesson.md',
      title: 'Lesson',
    });

    expect(html).not.toMatch(/generated-at|timestamp|updated-at|date/i);
  });
});
